CREATE TABLE ABSTRACT_LIST ( 
    ID bigint NOT NULL,
    DESCRIPTION varchar(200),
    NAME varchar(100),
    VISIBILITY varchar(20)
) type=InnoDB;

CREATE TABLE ABSTRACT_REPORTER ( 
    ID bigint NOT NULL,
    PLATFORM_ID bigint,
    NAME varchar(50)
) type=InnoDB;

CREATE TABLE ANALYSIS_JOB_CONFIG ( 
    ID bigint NOT NULL,
    STUDY_SUBSCRIPTION_ID bigint,
    ANALYSIS_METHOD_ID bigint
) type=InnoDB;

CREATE TABLE ANALYSIS_METHOD ( 
    ID bigint NOT NULL,
    DESCRIPTION varchar(200)
) type=InnoDB;

CREATE TABLE ANNOTATION_DEFINITION ( 
    CADSR_PUBLIC_ID bigint,
    CADSR_VERSION varchar(10),
    DISPLAY_NAME varchar(100),
    ID bigint NOT NULL,
    PREFERRED_DEFINITION varchar(500)
) type=InnoDB;

CREATE TABLE ANNOTATION_VALUE ( 
    ID bigint NOT NULL,
    VALUE varchar(50),
    STUDY_SUBJECT_ASSIGN_ID bigint,
    ANNOTATION_DEFINITION_ID bigint,
    IMAGE_SERIES_ID bigint,
    SAMPLE_ACQUISITION_ID bigint
) type=InnoDB;

CREATE TABLE ARRAY_DATA ( 
    ID bigint NOT NULL,
    ARRAY_ID bigint,
    ARRAY_DATA_MATRIX_ID bigint
) type=InnoDB;

CREATE TABLE ARRAY_DATA_MATRIX ( 
    ID bigint NOT NULL
) type=InnoDB;

CREATE TABLE ARRAY_DATA_MATRIX_REPORTERS ( 
    ID bigint NOT NULL,
    ARRAY_DATA_MATRIX_ID bigint,
    REPORTER_ID bigint
) type=InnoDB;

CREATE TABLE CRITERIA ( 
    ID bigint NOT NULL,
    TYPE varchar(50),
    COMPARATOR varchar(10),
    QUERY_ID bigint,
    ANNOTATION_DEFINITION_ID bigint,
    ANNOTATION_VALUE_ID bigint
) type=InnoDB;

CREATE TABLE GENE ( 
    ID bigint NOT NULL
) type=InnoDB;

CREATE TABLE GENE_EXPRESSION_REPORTER ( 
    ID bigint NOT NULL,
    GENE_ID bigint,
    ABSTRACT_REPORTER_ID bigint
) type=InnoDB;

CREATE TABLE IMAGE ( 
    ID bigint NOT NULL,
    IMAGE_SERIES_ID bigint
) type=InnoDB;

CREATE TABLE IMAGE_SERIES ( 
    ID bigint NOT NULL,
    IMAGE_STUDY_ID bigint
) type=InnoDB;

CREATE TABLE IMAGE_STUDY ( 
    ID bigint NOT NULL,
    STUDY_SUBJECT_ASSIGN_ID bigint
) type=InnoDB;

CREATE TABLE MICROARRAY ( 
    ID bigint NOT NULL,
    PLATFORM_ID bigint,
    SAMPLE_ID bigint
) type=InnoDB;

CREATE TABLE PERMISSABLE_VALUE ( 
    ID bigint NOT NULL,
    VALUE varchar(50),
    ANNOTATION_DEFINITION_ID bigint
) type=InnoDB;

CREATE TABLE PLATFORM ( 
    ID bigint NOT NULL
) type=InnoDB;

CREATE TABLE QUERY ( 
    ID bigint NOT NULL,
    DESCRIPTION varchar(200),
    NAME varchar(100),
    VISIBILITY varchar(20),
    STUDY_SUBSCRIPTION_ID bigint
) type=InnoDB;

CREATE TABLE SAMPLE ( 
    ID bigint NOT NULL,
    NAME varchar(50),
    SAMPLE_ACQUISITION_ID bigint
) type=InnoDB;

CREATE TABLE SAMPLE_ACQUISITION ( 
    ID bigint NOT NULL,
    STUDY_SUBJECT_ASSIGN_ID bigint,
    TIMEPOINT_ID bigint
) type=InnoDB;

CREATE TABLE STUDY ( 
    ID bigint NOT NULL,
    LONG_TITLE_TEXT varchar(200),
    SHORT_TITLE_TEXT varchar(50)
) type=InnoDB;

CREATE TABLE STUDY_IMAGE_ANNOTATIONS ( 
    ID bigint NOT NULL,
    STUDY_ID bigint,
    ANNOTATION_DEFINITION_ID bigint
) type=InnoDB;

CREATE TABLE STUDY_SAMPLE_ANNOTATIONS ( 
    ID bigint NOT NULL,
    STUDY_ID bigint,
    ANNOTATION_DEFINITION_ID bigint
) type=InnoDB;

CREATE TABLE STUDY_SUBJECT_ANNOTATIONS ( 
    ID bigint NOT NULL,
    STUDY_ID bigint,
    ANNOTATION_DEFINITION_ID bigint
) type=InnoDB;

CREATE TABLE STUDY_SUBJECT_ASSIGNMENT ( 
    ID bigint NOT NULL,
    STUDY_ID bigint,
    SUBJECT_ID bigint
) type=InnoDB;

CREATE TABLE STUDY_SUBSCRIPTION ( 
    ID bigint NOT NULL,
    USER_WORKSPACE_ID bigint,
    STUDY_ID bigint
) type=InnoDB;

CREATE TABLE SUBJECT ( 
    ID bigint NOT NULL
) type=InnoDB;

CREATE TABLE SUBJECT_LIST ( 
    ID bigint NOT NULL,
    STUDY_SUBSCRIPTION_ID bigint,
    ABSTRACT_LIST_ID bigint
) type=InnoDB;

CREATE TABLE SUBJECT_LIST_SUBJECT ( 
    ID bigint NOT NULL,
    SUBJECT_LIST_ID bigint,
    SUBJECT_ID bigint
) type=InnoDB;

CREATE TABLE TIMEPOINT ( 
    ID bigint NOT NULL,
    STUDY_ID bigint
) type=InnoDB;

CREATE TABLE USER_WORKSPACE ( 
    ID bigint NOT NULL,
    DEFAULT_STUDY_SUBSCRIPTION_ID bigint
) type=InnoDB;


ALTER TABLE ABSTRACT_LIST ADD CONSTRAINT PK_ABSTRACT_LIST 
    PRIMARY KEY (ID);


ALTER TABLE ABSTRACT_REPORTER ADD CONSTRAINT PK_ABSTRACT_REPORTER 
    PRIMARY KEY (ID);


ALTER TABLE ANALYSIS_JOB_CONFIG ADD CONSTRAINT PK_ANALYSIS_JOB_CONFIG 
    PRIMARY KEY (ID);


ALTER TABLE ANALYSIS_METHOD ADD CONSTRAINT PK_ANALYSIS_METHOD 
    PRIMARY KEY (ID);


ALTER TABLE ANNOTATION_DEFINITION ADD CONSTRAINT PK_ANNOTATION_DEFINITION 
    PRIMARY KEY (ID);


ALTER TABLE ANNOTATION_VALUE ADD CONSTRAINT PK_ANNOTATION_VALUE 
    PRIMARY KEY (ID);


ALTER TABLE ARRAY_DATA ADD CONSTRAINT PK_ARRAY_DATA 
    PRIMARY KEY (ID);


ALTER TABLE ARRAY_DATA_MATRIX ADD CONSTRAINT PK_ARRAY_DATA_MATRIX 
    PRIMARY KEY (ID);


ALTER TABLE ARRAY_DATA_MATRIX_REPORTERS ADD CONSTRAINT PK_ARRAY_DATA_MATRIX_REPORTERS 
    PRIMARY KEY (ID);


ALTER TABLE CRITERIA ADD CONSTRAINT PK_CRITERIA 
    PRIMARY KEY (ID);


ALTER TABLE GENE ADD CONSTRAINT PK_GENE 
    PRIMARY KEY (ID);


ALTER TABLE GENE_EXPRESSION_REPORTER ADD CONSTRAINT PK_GENE_EXPRESSION_REPORTER 
    PRIMARY KEY (ID);


ALTER TABLE IMAGE ADD CONSTRAINT PK_IMAGE 
    PRIMARY KEY (ID);


ALTER TABLE IMAGE_SERIES ADD CONSTRAINT PK_IMAGE_SERIES 
    PRIMARY KEY (ID);


ALTER TABLE IMAGE_STUDY ADD CONSTRAINT PK_IMAGE_STUDY 
    PRIMARY KEY (ID);


ALTER TABLE MICROARRAY ADD CONSTRAINT PK_ARRAY 
    PRIMARY KEY (ID);


ALTER TABLE PERMISSABLE_VALUE ADD CONSTRAINT PK_PERMISSABLE_VALUE 
    PRIMARY KEY (ID);


ALTER TABLE PLATFORM ADD CONSTRAINT PK_PLATFORM 
    PRIMARY KEY (ID);


ALTER TABLE QUERY ADD CONSTRAINT PK_QUERY 
    PRIMARY KEY (ID);


ALTER TABLE SAMPLE ADD CONSTRAINT PK_SAMPLE 
    PRIMARY KEY (ID);


ALTER TABLE SAMPLE_ACQUISITION ADD CONSTRAINT PK_SAMPLE_ACQUISITION 
    PRIMARY KEY (ID);


ALTER TABLE STUDY ADD CONSTRAINT PK_STUDY 
    PRIMARY KEY (ID);


ALTER TABLE STUDY_IMAGE_ANNOTATIONS ADD CONSTRAINT PK_STUDY_IMAGE_ANNOTATIONS 
    PRIMARY KEY (ID);


ALTER TABLE STUDY_SAMPLE_ANNOTATIONS ADD CONSTRAINT PK_STUDY_SAMPLE_ANNOTATIONS 
    PRIMARY KEY (ID);


ALTER TABLE STUDY_SUBJECT_ANNOTATIONS ADD CONSTRAINT PK_STUDY_CLINICAL_ANNOTATIONS 
    PRIMARY KEY (ID);


ALTER TABLE STUDY_SUBJECT_ASSIGNMENT ADD CONSTRAINT PK_STUDY_SUBJECT_ASSIGNMENT 
    PRIMARY KEY (ID);


ALTER TABLE STUDY_SUBSCRIPTION ADD CONSTRAINT PK_STUDY_SUBSCRIPTION 
    PRIMARY KEY (ID);


ALTER TABLE SUBJECT ADD CONSTRAINT PK_SUBJECT 
    PRIMARY KEY (ID);


ALTER TABLE SUBJECT_LIST ADD CONSTRAINT PK_SUBJECT_LIST 
    PRIMARY KEY (ID);


ALTER TABLE SUBJECT_LIST_SUBJECT ADD CONSTRAINT PK_SUBJECT_LIST_SUBJECT 
    PRIMARY KEY (ID);


ALTER TABLE TIMEPOINT ADD CONSTRAINT PK_TIMEPOINT 
    PRIMARY KEY (ID);


ALTER TABLE USER_WORKSPACE ADD CONSTRAINT PK_USER_WORKSPACE 
    PRIMARY KEY (ID);





ALTER TABLE ABSTRACT_REPORTER ADD CONSTRAINT FK_ABSTRACT_REPORTER_PLATFORM 
    FOREIGN KEY (PLATFORM_ID) REFERENCES PLATFORM (ID);

ALTER TABLE ANALYSIS_JOB_CONFIG ADD CONSTRAINT FK_ANALYSIS_JOB_CONFIG_ANALYSIS_METHOD 
    FOREIGN KEY (ANALYSIS_METHOD_ID) REFERENCES ANALYSIS_METHOD (ID);

ALTER TABLE ANALYSIS_JOB_CONFIG ADD CONSTRAINT FK_ANALYSIS_JOB_CONFIG_STUDY_SUBSCRIPTION 
    FOREIGN KEY (STUDY_SUBSCRIPTION_ID) REFERENCES STUDY_SUBSCRIPTION (ID);

ALTER TABLE ANNOTATION_VALUE ADD CONSTRAINT FK_ANNOTATION_VALUE_ANNOTATION_DEFINITION 
    FOREIGN KEY (ANNOTATION_DEFINITION_ID) REFERENCES ANNOTATION_DEFINITION (ID);

ALTER TABLE ANNOTATION_VALUE ADD CONSTRAINT FK_ANNOTATION_VALUE_IMAGE_SERIES 
    FOREIGN KEY (IMAGE_SERIES_ID) REFERENCES IMAGE_SERIES (ID);

ALTER TABLE ANNOTATION_VALUE ADD CONSTRAINT FK_ANNOTATION_VALUE_SAMPLE_ACQUISITION 
    FOREIGN KEY (SAMPLE_ACQUISITION_ID) REFERENCES SAMPLE_ACQUISITION (ID);

ALTER TABLE ANNOTATION_VALUE ADD CONSTRAINT FK_ANNOTATION_VALUE_STUDY_SUBJECT_ASSIGNMENT 
    FOREIGN KEY (STUDY_SUBJECT_ASSIGN_ID) REFERENCES STUDY_SUBJECT_ASSIGNMENT (ID);

ALTER TABLE ARRAY_DATA ADD CONSTRAINT FK_ARRAY_DATA_ARRAY 
    FOREIGN KEY (ARRAY_ID) REFERENCES MICROARRAY (ID);

ALTER TABLE ARRAY_DATA ADD CONSTRAINT FK_ARRAY_DATA_ARRAY_DATA_MATRIX 
    FOREIGN KEY (ARRAY_DATA_MATRIX_ID) REFERENCES ARRAY_DATA_MATRIX (ID);

ALTER TABLE ARRAY_DATA_MATRIX_REPORTERS ADD CONSTRAINT FK_ARRAY_DATA_MATRIX_REPORTERS_ABSTRACT_REPORTER 
    FOREIGN KEY (REPORTER_ID) REFERENCES ABSTRACT_REPORTER (ID);

ALTER TABLE ARRAY_DATA_MATRIX_REPORTERS ADD CONSTRAINT FK_ARRAY_DATA_MATRIX_REPORTERS_ARRAY_DATA_MATRIX 
    FOREIGN KEY (ARRAY_DATA_MATRIX_ID) REFERENCES ARRAY_DATA_MATRIX (ID);

ALTER TABLE CRITERIA ADD CONSTRAINT FK_CRITERIA_ANNOTATION_DEFINITION 
    FOREIGN KEY (ANNOTATION_DEFINITION_ID) REFERENCES ANNOTATION_DEFINITION (ID);

ALTER TABLE CRITERIA ADD CONSTRAINT FK_CRITERIA_ANNOTATION_VALUE 
    FOREIGN KEY (ANNOTATION_VALUE_ID) REFERENCES ANNOTATION_VALUE (ID);

ALTER TABLE CRITERIA ADD CONSTRAINT FK_CRITERIA_QUERY 
    FOREIGN KEY (QUERY_ID) REFERENCES QUERY (ID);

ALTER TABLE GENE_EXPRESSION_REPORTER ADD CONSTRAINT FK_GENE_EXPRESSION_REPORTER_ABSTRACT_REPORTER 
    FOREIGN KEY (ABSTRACT_REPORTER_ID) REFERENCES ABSTRACT_REPORTER (ID);

ALTER TABLE GENE_EXPRESSION_REPORTER ADD CONSTRAINT FK_GENE_EXPRESSION_REPORTER_GENE 
    FOREIGN KEY (GENE_ID) REFERENCES GENE (ID);

ALTER TABLE IMAGE ADD CONSTRAINT FK_IMAGE_IMAGE_SERIES 
    FOREIGN KEY (IMAGE_SERIES_ID) REFERENCES IMAGE_SERIES (ID);

ALTER TABLE IMAGE_SERIES ADD CONSTRAINT FK_IMAGE_SERIES_IMAGE_STUDY 
    FOREIGN KEY (IMAGE_STUDY_ID) REFERENCES IMAGE_STUDY (ID);

ALTER TABLE IMAGE_STUDY ADD CONSTRAINT FK_IMAGE_STUDY_STUDY_SUBJECT_ASSIGNMENT 
    FOREIGN KEY (STUDY_SUBJECT_ASSIGN_ID) REFERENCES STUDY_SUBJECT_ASSIGNMENT (ID);

ALTER TABLE MICROARRAY ADD CONSTRAINT FK_ARRAY_PLATFORM 
    FOREIGN KEY (PLATFORM_ID) REFERENCES PLATFORM (ID);

ALTER TABLE MICROARRAY ADD CONSTRAINT FK_ARRAY_SAMPLE 
    FOREIGN KEY (SAMPLE_ID) REFERENCES SAMPLE (ID);

ALTER TABLE PERMISSABLE_VALUE ADD CONSTRAINT FK_PERMISSABLE_VALUE_ANNOTATION_DEFINITION 
    FOREIGN KEY (ANNOTATION_DEFINITION_ID) REFERENCES ANNOTATION_DEFINITION (ID);

ALTER TABLE QUERY ADD CONSTRAINT FK_QUERY_STUDY_SUBSCRIPTION 
    FOREIGN KEY (STUDY_SUBSCRIPTION_ID) REFERENCES STUDY_SUBSCRIPTION (ID);

ALTER TABLE SAMPLE ADD CONSTRAINT FK_SAMPLE_SAMPLE_ACQUISITION 
    FOREIGN KEY (SAMPLE_ACQUISITION_ID) REFERENCES SAMPLE_ACQUISITION (ID);

ALTER TABLE SAMPLE_ACQUISITION ADD CONSTRAINT FK_SAMPLE_ACQUISITION_STUDY_SUBJECT_ASSIGNMENT 
    FOREIGN KEY (STUDY_SUBJECT_ASSIGN_ID) REFERENCES STUDY_SUBJECT_ASSIGNMENT (ID);

ALTER TABLE SAMPLE_ACQUISITION ADD CONSTRAINT FK_SAMPLE_ACQUISITION_TIMEPOINT 
    FOREIGN KEY (TIMEPOINT_ID) REFERENCES TIMEPOINT (ID);

ALTER TABLE STUDY_IMAGE_ANNOTATIONS ADD CONSTRAINT FK_STUDY_IMAGE_ANNOTATIONS_ANNOTATION_DEFINITION 
    FOREIGN KEY (ANNOTATION_DEFINITION_ID) REFERENCES ANNOTATION_DEFINITION (ID);

ALTER TABLE STUDY_IMAGE_ANNOTATIONS ADD CONSTRAINT FK_STUDY_IMAGE_ANNOTATIONS_STUDY 
    FOREIGN KEY (STUDY_ID) REFERENCES STUDY (ID);

ALTER TABLE STUDY_SAMPLE_ANNOTATIONS ADD CONSTRAINT FK_STUDY_SAMPLE_ANNOTATIONS_ANNOTATION_DEFINITION 
    FOREIGN KEY (ANNOTATION_DEFINITION_ID) REFERENCES ANNOTATION_DEFINITION (ID);

ALTER TABLE STUDY_SAMPLE_ANNOTATIONS ADD CONSTRAINT FK_STUDY_SAMPLE_ANNOTATIONS_STUDY 
    FOREIGN KEY (STUDY_ID) REFERENCES STUDY (ID);

ALTER TABLE STUDY_SUBJECT_ANNOTATIONS ADD CONSTRAINT FK_STUDY_CLINICAL_ANNOTATIONS_ANNOTATION_DEFINITION 
    FOREIGN KEY (ANNOTATION_DEFINITION_ID) REFERENCES ANNOTATION_DEFINITION (ID);

ALTER TABLE STUDY_SUBJECT_ANNOTATIONS ADD CONSTRAINT FK_STUDY_CLINICAL_ANNOTATIONS_STUDY 
    FOREIGN KEY (STUDY_ID) REFERENCES STUDY (ID);

ALTER TABLE STUDY_SUBJECT_ASSIGNMENT ADD CONSTRAINT FK_STUDY_SUBJECT_ASSIGNMENT_STUDY 
    FOREIGN KEY (STUDY_ID) REFERENCES STUDY (ID);

ALTER TABLE STUDY_SUBJECT_ASSIGNMENT ADD CONSTRAINT FK_STUDY_SUBJECT_ASSIGNMENT_SUBJECT 
    FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT (ID);

ALTER TABLE STUDY_SUBSCRIPTION ADD CONSTRAINT FK_STUDY_SUBSCRIPTION_STUDY 
    FOREIGN KEY (STUDY_ID) REFERENCES STUDY (ID);

ALTER TABLE STUDY_SUBSCRIPTION ADD CONSTRAINT FK_STUDY_SUBSCRIPTION_USER_WORKSPACE 
    FOREIGN KEY (USER_WORKSPACE_ID) REFERENCES USER_WORKSPACE (ID);

ALTER TABLE SUBJECT_LIST ADD CONSTRAINT FK_SUBJECT_LIST_ABSTRACT_LIST 
    FOREIGN KEY (ABSTRACT_LIST_ID) REFERENCES ABSTRACT_LIST (ID);

ALTER TABLE SUBJECT_LIST ADD CONSTRAINT FK_SUBJECT_LIST_STUDY_SUBSCRIPTION 
    FOREIGN KEY (STUDY_SUBSCRIPTION_ID) REFERENCES STUDY_SUBSCRIPTION (ID);

ALTER TABLE SUBJECT_LIST_SUBJECT ADD CONSTRAINT FK_SUBJECT_LIST_SUBJECT_SUBJECT 
    FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT (ID);

ALTER TABLE SUBJECT_LIST_SUBJECT ADD CONSTRAINT FK_SUBJECT_LIST_SUBJECT_SUBJECT_LIST 
    FOREIGN KEY (SUBJECT_LIST_ID) REFERENCES SUBJECT_LIST (ID);

ALTER TABLE TIMEPOINT ADD CONSTRAINT FK_TIMEPOINT_STUDY 
    FOREIGN KEY (STUDY_ID) REFERENCES STUDY (ID);

ALTER TABLE USER_WORKSPACE ADD CONSTRAINT FK_USER_WORKSPACE_STUDY_SUBSCRIPTION 
    FOREIGN KEY (DEFAULT_STUDY_SUBSCRIPTION_ID) REFERENCES STUDY_SUBSCRIPTION (ID);
