alter table STUDY_CONFIGURATION drop foreign key FK_STUDY_CONFIGURATION_STUDY;
alter table ABSTRACT_CLINICAL_SOURCE_CONFIGURATION drop foreign key FKBAE4F601DDCA2BE1;
alter table ABSTRACT_CLINICAL_SOURCE_CONFIGURATION drop foreign key FKBAE4F601C0ADCD6;
alter table ANNOTATION_FIELD_DESCRIPTOR drop foreign key FK5D1F2F04AF56BCDA;

drop table if exists STUDY_CONFIGURATION;
drop table if exists ABSTRACT_CLINICAL_SOURCE_CONFIGURATION;
drop table if exists ANNOTATION_FIELD_DESCRIPTOR;