ALTER TABLE ABSTRACT_PERSISTED_ANALYSIS_JOB MODIFY COLUMN RESULTS_ZIP_FILE_PATH VARCHAR(255);
ALTER TABLE ABSTRACT_PERSISTED_ANALYSIS_JOB ADD COLUMN INPUT_ZIP_FILE_PATH VARCHAR(255) AFTER MAIN_GRID_URL;
ALTER TABLE PLATFORM_CONFIGURATION ADD COLUMN PLATFORM_TYPE VARCHAR(50) AFTER PLATFORM_ID;