CREATE TABLE LOG_ENTRY (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  SYSTEM_LOG_MESSAGE VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  USERNAME VARCHAR(55),
  LOG_DATE DATETIME,
  STUDY_CONFIGURATION_ID BIGINT,
  LIST_INDEX INTEGER,
  PRIMARY KEY (ID)
) ENGINE = InnoDB;

ALTER TABLE LOG_ENTRY 
    ADD CONSTRAINT FK_LOG_ENTRY_STUDY_CONFIGURATION FOREIGN KEY (STUDY_CONFIGURATION_ID) REFERENCES STUDY_CONFIGURATION (ID);
    
INSERT INTO LOG_ENTRY (STUDY_CONFIGURATION_ID) SELECT ID FROM STUDY_CONFIGURATION;

UPDATE LOG_ENTRY SET SYSTEM_LOG_MESSAGE = 'This is the initial log message for this study. This study was created before the log feature was available.', LIST_INDEX = 0, USERNAME = 'SYSTEM', LOG_DATE = sysdate() where SYSTEM_LOG_MESSAGE is null;