ALTER TABLE SURVIVAL_VALUE_DEFINITION 
 ADD COLUMN SURVIVAL_LENGTH_ID BIGINT(20),
 ADD COLUMN SURVIVAL_STATUS_ID BIGINT(20),
 ADD COLUMN SURVIVAL_LENGTH_UNITS VARCHAR(30),
 ADD COLUMN VALUE_FOR_CENSORED VARCHAR(55);
 
UPDATE SURVIVAL_VALUE_DEFINITION SET SURVIVAL_VALUE_TYPE = "DATE";