alter table ABSTRACT_CLINICAL_SOURCE_CONFIGURATION drop foreign key FKBAE4F601C0ADCD6;
alter table ANNOTATION_FIELD_DESCRIPTOR drop foreign key FK5D1F2F04AF56BCDA;
alter table ANNOTATION_FIELD_DESCRIPTOR_KEYWORDS drop foreign key FK95E53685D02FEB76;
alter table ANNOTATION_FILE drop foreign key FKB2E3F48C2F7719A9;
alter table ANNOTATION_FILE drop foreign key FKB2E3F48CF74C0BEF;
alter table DELIMITED_TEXT_CLINICAL_SOURCE_CONFIGURATION drop foreign key FKCA9C89F268A868E8;
alter table DELIMITED_TEXT_CLINICAL_SOURCE_CONFIGURATION drop foreign key FKCA9C89F25F5B0F92;
alter table FILE_COLUMN drop foreign key FK7BBDF379DDCA2BE1;
alter table FILE_COLUMN drop foreign key FK7BBDF37968A868E8;
alter table STUDY_CONFIGURATION drop foreign key FK1CC8D8C0A0CEA12A;

drop table if exists ABSTRACT_CLINICAL_SOURCE_CONFIGURATION;
drop table if exists ANNOTATION_FIELD_DESCRIPTOR;
drop table if exists ANNOTATION_FIELD_DESCRIPTOR_KEYWORDS;
drop table if exists ANNOTATION_FILE;
drop table if exists DELIMITED_TEXT_CLINICAL_SOURCE_CONFIGURATION;
drop table if exists FILE_COLUMN;
drop table if exists STUDY_CONFIGURATION;