function  WWHBookData_Files(P)
{
P.fA("Welcome to caIntegrator Online Help","Welcome.1.1.html");
P.fA("Online Help Tips","OnlineHelpBoilerplate.2.1.html");
P.fA("Getting Started with caIntegrator","Getting_Started.3.1.html");
P.fA("About caIntegrator","Getting_Started.3.2.html");
P.fA("Registering as a New caIntegrator User","Getting_Started.3.3.html");
P.fA("Welcome to the caIntegrator Workspace","Getting_Started.3.4.html");
P.fA("caIntegrator Functions","Getting_Started.3.5.html");
P.fA("Viewing Existing Studies","Getting_Started.3.6.html");
P.fA("Data Dictionary","Getting_Started.3.7.html");
P.fA("Study Log","Getting_Started.3.8.html");
P.fA("Using Online Help","Getting_Started.3.9.html");
P.fA("Logging Out","Getting_Started.3.10.html");
P.fA("Application Support","Getting_Started.3.11.html");
P.fA("Creating a New Study","CreatingNewStudy.4.1.html");
P.fA("Creating a Study \u2013 Overview","CreatingNewStudy.4.2.html");
P.fA("Configuring and Deploying a Study","CreatingNewStudy.4.3.html");
P.fA("Creating/Editing a Study","CreatingNewStudy.4.4.html");
P.fA("Viewing/Editing a Log","CreatingNewStudy.4.5.html");
P.fA("Working with Annotations \u2013 An Overview","CreatingNewStudy.4.6.html");
P.fA("Adding An Annotation Group","CreatingNewStudy.4.7.html");
P.fA("Editing an Annotation Group","CreatingNewStudy.4.8.html");
P.fA("Adding Subject Annotation Data","CreatingNewStudy.4.9.html");
P.fA("Define Fields Page for Editing Annotations","CreatingNewStudy.4.10.html");
P.fA("Assigning An Identifier or Annotation","CreatingNewStudy.4.11.html");
P.fA("Searching for Annotation Definitions","CreatingNewStudy.4.12.html");
P.fA("Defining Survival Values","CreatingNewStudy.4.13.html");
P.fA("Adding/Editing Genomic Data","CreatingNewStudy.4.14.html");
P.fA("Mapping Genomic Data to Subject Annotation Data","CreatingNewStudy.4.15.html");
P.fA("Creating a Mapping File","CreatingNewStudy.4.16.html");
P.fA("Steps for Mapping Genomic Data","CreatingNewStudy.4.17.html");
P.fA("Uploading Control Samples","CreatingNewStudy.4.18.html");
P.fA("Configuring Copy Number Data","CreatingNewStudy.4.19.html");
P.fA("Remapping Copy Number Data in a Deployed Study","CreatingNewStudy.4.20.html");
P.fA("Working with Imaging Data","CreatingNewStudy.4.21.html");
P.fA("Adding or Editing Imaging Data Files from NBIA","CreatingNewStudy.4.22.html");
P.fA("Adding or Editing Image Annotations","CreatingNewStudy.4.23.html");
P.fA("Adding External Links","CreatingNewStudy.4.24.html");
P.fA("Deploying the Study","CreatingNewStudy.4.25.html");
P.fA("Managing a Study","CreatingNewStudy.4.26.html");
P.fA("Managing Platforms","CreatingNewStudy.4.27.html");
P.fA("Searching a caIntegrator Study","SearchingWithinAStudy.5.1.html");
P.fA("Search Overview","SearchingWithinAStudy.5.2.html");
P.fA("Searching a Study","SearchingWithinAStudy.5.3.html");
P.fA("Annotation and Image Data Searches","SearchingWithinAStudy.5.4.html");
P.fA("Gene Expression Data Searches","SearchingWithinAStudy.5.5.html");
P.fA("Copy Number Searches","SearchingWithinAStudy.5.6.html");
P.fA("Choosing Genes","SearchingWithinAStudy.5.7.html");
P.fA("Query Results","SearchingWithinAStudy.5.8.html");
P.fA("Results Type Tab","SearchingWithinAStudy.5.9.html");
P.fA("Sorting Tab","SearchingWithinAStudy.5.10.html");
P.fA("Managing Queries","SearchingWithinAStudy.5.11.html");
P.fA("Saving a Query","SearchingWithinAStudy.5.12.html");
P.fA("Editing a Query","SearchingWithinAStudy.5.13.html");
P.fA("Exporting Query Results","SearchingWithinAStudy.5.14.html");
P.fA("Viewing Query Results","View%20Search%20Results.6.1.html");
P.fA("Query Results Overview","View%20Search%20Results.6.2.html");
P.fA("Browsing Query Results","View%20Search%20Results.6.3.html");
P.fA("Subject Annotation and Imaging Data","View%20Search%20Results.6.4.html");
P.fA("Gene Expression Data","View%20Search%20Results.6.5.html");
P.fA("Copy Number Data","View%20Search%20Results.6.6.html");
P.fA("Creating a Gene or Subject List","View%20Search%20Results.6.7.html");
P.fA("Choosing Genes","View%20Search%20Results.6.8.html");
P.fA("Editing a Gene or Subject List","View%20Search%20Results.6.9.html");
P.fA("Editing a GISTIC Analysis","View%20Search%20Results.6.10.html");
P.fA("Expanding Imaging Data Results","View%20Search%20Results.6.11.html");
P.fA("caIntegrator and NBIA","View%20Search%20Results.6.12.html");
P.fA("Retrieving DICOM Images","View%20Search%20Results.6.13.html");
P.fA("Example of Retrieving Images:","View%20Search%20Results.6.14.html");
P.fA("Relationship of Patient to Study to Series to Images","View%20Search%20Results.6.15.html");
P.fA("Exporting Data","View%20Search%20Results.6.16.html");
P.fA("Analyzing Studies","PerformingAnalysis.7.1.html");
P.fA("Data Analysis Overview","PerformingAnalysis.7.2.html");
P.fA("Creating Kaplan-Meier Plots","PerformingAnalysis.7.3.html");
P.fA("K-M Plot for Annotations","PerformingAnalysis.7.4.html");
P.fA("K-M Plot for Gene Expression","PerformingAnalysis.7.5.html");
P.fA("KM Plot from Gene Expression Data Display","PerformingAnalysis.7.6.html");
P.fA("K-M Plot for Queries and Saved Lists","PerformingAnalysis.7.7.html");
P.fA("K-M Plot for Queries Display","PerformingAnalysis.7.8.html");
P.fA("Creating Gene Expression Plots","PerformingAnalysis.7.9.html");
P.fA("Gene Expression Value Plot for Annotation","PerformingAnalysis.7.10.html");
P.fA("Gene Expression Plot for Annotation Display","PerformingAnalysis.7.11.html");
P.fA("Gene Expression Value Plot for Genomic Queries","PerformingAnalysis.7.12.html");
P.fA("Gene Expression Value Plot for Annotation and Saved List Queries","PerformingAnalysis.7.13.html");
P.fA("Gene Expression Plot for Saved Queries Display","PerformingAnalysis.7.14.html");
P.fA("Understanding a Gene Expression Plot","PerformingAnalysis.7.15.html");
P.fA("Choosing Genes","PerformingAnalysis.7.16.html");
P.fA("Analyzing Data with GenePattern","PerformingAnalysis.7.17.html");
P.fA("GenePattern Modules","PerformingAnalysis.7.18.html");
P.fA("Comparative Marker Selection (CMS) Analysis","PerformingAnalysis.7.19.html");
P.fA("Principal Component Analysis (PCA)","PerformingAnalysis.7.20.html");
P.fA("GISTIC-Supported Analysis","PerformingAnalysis.7.21.html");
P.fA("Viewing Data with the Integrative Genomics Viewer","PerformingAnalysis.7.22.html");
P.fA("Viewing Data with Heat Map Viewer","PerformingAnalysis.7.23.html");
P.fA("Java for IGV and Heat Map Viewer","PerformingAnalysis.7.24.html");
P.fA("Administering User Accounts","User%20Admin.8.1.html");
P.fA("Administering caIntegrator User Accounts Using UPT","User%20Admin.8.2.html");
P.fA("Steps for Creating User Access to caIntegrator","User%20Admin.8.3.html");
P.fA("Creating a New caIntegrator User","User%20Admin.8.4.html");
P.fA("Creating a New User Group","User%20Admin.8.5.html");
P.fA("Creating a New Protection Group","User%20Admin.8.6.html");
P.fA("Assigning a User Group to a Protection Group","User%20Admin.8.7.html");
P.fA("Adding a User to a User Group","User%20Admin.8.8.html");
P.fA("Changing a User Password","User%20Admin.8.9.html");
P.fA("Data Import Configurations","appdx%20data%20import.9.1.html");
P.fA("Subject Annotation Data Configuration","appdx%20data%20import.9.2.html");
P.fA("Delimited-Text Annotation Import","appdx%20data%20import.9.3.html");
P.fA("Annotation Field Configuration","appdx%20data%20import.9.4.html");
P.fA("Sample Data Configuration","appdx%20data%20import.9.5.html");
P.fA("Genomic Data Configuration","appdx%20data%20import.9.6.html");
P.fA("Supplemental Files Configuration","appdx%20data%20import.9.7.html");
P.fA("Single Sample Format","appdx%20data%20import.9.8.html");
P.fA("Multiple Sample Format","appdx%20data%20import.9.9.html");
P.fA("Imaging Data Configuration","appdx%20data%20import.9.10.html");
P.fA("Glossary","Glossary.10.1.html");
P.fA("NCICB Application Support","Application%20Support.11.1.html");
}
