create table ANNOTATION_GROUP (
    ID bigint not null auto_increment, 
    STUDY_ID bigint, 
    NAME varchar(255),
    DESCRIPTION varchar(500),
    ANNOTATION_ENTITY_TYPE varchar(100),
    primary key (ID)
) ENGINE=InnoDB;

ALTER TABLE ANNOTATION_GROUP ADD CONSTRAINT FK_ANNOTATION_GROUP_STUDY
    FOREIGN KEY (STUDY_ID) REFERENCES STUDY (ID);

ALTER TABLE ANNOTATION_FIELD_DESCRIPTOR ADD COLUMN ANNOTATION_GROUP_ID BIGINT(20) AFTER ANNOTATION_DEFINITION_ID,
ADD COLUMN HAS_VALIDATION_ERRORS TINYINT(4) AFTER ANNOTATION_GROUP_ID,
ADD COLUMN USE_PERMISSIBLE_VALUES TINYINT(4) AFTER HAS_VALIDATION_ERRORS;

ALTER TABLE ANNOTATION_FIELD_DESCRIPTOR ADD CONSTRAINT FK_ANNOTATION_FIELD_DESCRIPTOR_GROUP 
    FOREIGN KEY (ANNOTATION_GROUP_ID) REFERENCES ANNOTATION_GROUP (ID);
    
ALTER TABLE RESULT_COLUMN ADD COLUMN ANNOTATION_FIELD_DESCRIPTOR_ID BIGINT(20) AFTER ANNOTATION_DEFINITION_ID;

ALTER TABLE RESULT_COLUMN ADD CONSTRAINT FK_RESULT_COLUMN_ANNOTATION_FIELD_DESCRIPTOR 
    FOREIGN KEY (ANNOTATION_FIELD_DESCRIPTOR_ID) references ANNOTATION_FIELD_DESCRIPTOR (ID);
    
ALTER TABLE ABSTRACT_ANNOTATION_CRITERION ADD COLUMN ANNOTATION_FIELD_DESCRIPTOR_ID BIGINT(20) AFTER ANNOTATION_DEFINITION_ID;
ALTER TABLE ABSTRACT_ANNOTATION_CRITERION ADD CONSTRAINT FK_ABSTRACT_ANNOTATION_CRITERION_ANNOTATION_FIELD_DESCRIPTOR 
    FOREIGN KEY (ANNOTATION_FIELD_DESCRIPTOR_ID) references ANNOTATION_FIELD_DESCRIPTOR (ID);