ALTER TABLE ABSTRACT_CLINICAL_SOURCE_CONFIGURATION ADD COLUMN LAST_MODIFIED_DATE DATETIME AFTER LIST_INDEX;
ALTER TABLE IMAGE_DATA_SOURCE_CONFIGURATION ADD COLUMN LAST_MODIFIED_DATE DATETIME AFTER LIST_INDEX;
ALTER TABLE GENOMIC_DATA_SOURCE_CONFIGURATION ADD COLUMN LAST_MODIFIED_DATE DATETIME AFTER LIST_INDEX;
ALTER TABLE QUERY ADD COLUMN LAST_MODIFIED_DATE DATETIME AFTER VISIBILITY;
ALTER TABLE ABSTRACT_LIST ADD COLUMN LAST_MODIFIED_DATE DATETIME AFTER VISIBILITY;