ALTER TABLE GENOMIC_DATA_SOURCE_CONFIGURATION ADD COLUMN TECHNICAL_REPLICATES_CENTRAL_TENDENCY VARCHAR(20) AFTER SAMPLE_MAPPING_FILE_PATH;

UPDATE GENOMIC_DATA_SOURCE_CONFIGURATION SET TECHNICAL_REPLICATES_CENTRAL_TENDENCY = 'MEAN';

CREATE TABLE SAMPLE_REPORTERS_HIGH_VARIANCE
(
    SAMPLE_ID BIGINT NOT NULL,
    ABSTRACT_REPORTER_ID BIGINT NOT NULL,
    PRIMARY KEY (SAMPLE_ID, ABSTRACT_REPORTER_ID),
    KEY (SAMPLE_ID),
    KEY (ABSTRACT_REPORTER_ID)
) TYPE=InnoDB;

ALTER TABLE SAMPLE_REPORTERS_HIGH_VARIANCE ADD CONSTRAINT FK_SAMPLE_REPORTERS_HIGH_VARIANCE_SAMPLE
    FOREIGN KEY (SAMPLE_ID) REFERENCES SAMPLE (ID);

ALTER TABLE SAMPLE_REPORTERS_HIGH_VARIANCE ADD CONSTRAINT FK_SAMPLE_REPORTERS_HIGH_VARIANCE_REPORTER
    FOREIGN KEY (ABSTRACT_REPORTER_ID) REFERENCES ABSTRACT_REPORTER (ID);