ALTER TABLE SUBJECT_LIST_SUBJECT DROP FOREIGN KEY FK_SUBJECT_LIST_SUBJECT_SUBJECT;
ALTER TABLE SUBJECT_LIST_SUBJECT DROP FOREIGN KEY FK_SUBJECT_LIST_SUBJECT_SUBJECT_LIST;

DROP TABLE IF EXISTS SUBJECT_LIST_SUBJECT;

CREATE TABLE SUBJECT_IDENTIFIER 
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    SUBJECT_LIST_ID BIGINT,
    IDENTIFIER varchar(50),
    primary key (ID)
) Engine=InnoDB;

ALTER TABLE SUBJECT_IDENTIFIER ADD CONSTRAINT FK_SUBJECT_IDENTIFIER_SUBJECT_LIST
    FOREIGN KEY (SUBJECT_LIST_ID) REFERENCES SUBJECT_LIST (ID);

CREATE TABLE SUBJECT_LIST_CRITERION 
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    primary key (ID)
) Engine=InnoDB;

CREATE TABLE SUBJECT_LIST_CRITERIA_SUBJECT_LIST 
(
    SUBJECT_LIST_CRITERION_ID bigint not null, 
    SUBJECT_LIST_ID bigint not null,
    PRIMARY KEY (SUBJECT_LIST_CRITERION_ID, SUBJECT_LIST_ID)
) Engine=InnoDB;

ALTER TABLE SUBJECT_LIST_CRITERIA_SUBJECT_LIST ADD CONSTRAINT FK_SUBJECT_LIST_CRITERIA_SUBJECT_LIST_CRITERION 
    FOREIGN KEY (SUBJECT_LIST_CRITERION_ID) references SUBJECT_LIST_CRITERION (ID);
ALTER TABLE SUBJECT_LIST_CRITERIA_SUBJECT_LIST ADD CONSTRAINT FK_SUBJECT_LIST_CRITERIA_SUBJECT_LIST_SUBJECT 
    FOREIGN KEY (SUBJECT_LIST_ID) references SUBJECT_LIST (ID);
