alter table PLATFORM_CONFIGURATION add PLATFORM_CHANNEL_TYPE varchar(255);
update PLATFORM_CONFIGURATION set PLATFORM_CHANNEL_TYPE = "ONE_COLOR"
    where PLATFORM_TYPE = "AFFYMETRIX_GENE_EXPRESSION" or PLATFORM_TYPE = "AFFYMETRIX_COPY_NUMBER";