ALTER TABLE ANNOTATION_FILE DROP FOREIGN KEY FK_ANNOTATION_FILE_IDENTIFIER_COLUMN;
ALTER TABLE ANNOTATION_FILE DROP FOREIGN KEY FK_ANNOTATION_FILE_TIMEPOINT_COLUMN;
ALTER TABLE ANNOTATION_FILE DROP COLUMN IDENTIFIER_COLUMN_ID;
ALTER TABLE ANNOTATION_FILE DROP COLUMN TIMEPOINT_COLUMN_ID;