function FileData_Pairs(x)
{
x.t("icons","search");
x.t("describes","reports");
x.t("results","overview");
x.t("results","high");
x.t("results","i-spy");
x.t("results","viewing");
x.t("results","section");
x.t("overview","using");
x.t("high","order");
x.t("i-spy","report");
x.t("i-spy","returns");
x.t("search","results");
x.t("queries","high");
x.t("viewing","results");
x.t("report","icons");
x.t("section","describes");
x.t("section","include");
x.t("reports","search");
x.t("analyses","topics");
x.t("include","following");
x.t("topics","section");
x.t("order","analyses");
x.t("order","analysis");
x.t("following","results");
x.t("using","i-spy");
x.t("returns","queries");
x.t("analysis","results");
}
