function FileData_Pairs(x)
{
x.t("annotation","genomic");
x.t("describes","caintegrator");
x.t("subject","annotation");
x.t("kaplan-meier","plots");
x.t("overview","creating");
x.t("gene","expression");
x.t("analyze","data");
x.t("studies","deployed");
x.t("studies","analyzing");
x.t("studies","section");
x.t("creating","kaplan-meier");
x.t("creating","gene");
x.t("deployed","caintegrator");
x.t("analyzing","studies");
x.t("analyzing","data");
x.t("section","describes");
x.t("section","include");
x.t("include","following");
x.t("tools","analyze");
x.t("caintegrator","tools");
x.t("caintegrator","topics");
x.t("expression","plots");
x.t("data","subject");
x.t("data","genepattern");
x.t("data","analysis");
x.t("topics","section");
x.t("following","data");
x.t("plots","creating");
x.t("plots","analyzing");
x.t("analysis","overview");
x.t("genomic","studies");
}
