function FileData_Pairs(x)
{
x.t("below","information");
x.t("results","display");
x.t("results","viewing");
x.t("results","query");
x.t("results","browsing");
x.t("search","follow");
x.t("display","depend");
x.t("depend","upon");
x.t("viewing","query");
x.t("follow","links");
x.t("upon","criteria");
x.t("established","search");
x.t("query","results");
x.t("information","category");
x.t("data","searched");
x.t("browsing","query");
x.t("links","below");
x.t("criteria","established");
x.t("category","data");
}
