function FileData_Pairs(x)
{
x.t("searching","caintegrator2");
x.t("introduce","caintegrator2");
x.t("study","viewing");
x.t("study","using");
x.t("user","account");
x.t("getting","started");
x.t("new","study");
x.t("need","know");
x.t("results","analyzing");
x.t("creating","new");
x.t("studies","user");
x.t("account","administration");
x.t("welcome","caintegrator2");
x.t("started","caintegrator2");
x.t("know","caintegrator2");
x.t("viewing","query");
x.t("workspace","searching");
x.t("analyzing","studies");
x.t("online","help");
x.t("help","welcome");
x.t("help","following");
x.t("query","results");
x.t("topics","introduce");
x.t("administration","using");
x.t("following","topics");
x.t("using","online");
x.t("using","caintegrator2");
x.t("caintegrator2","study");
x.t("caintegrator2","getting");
x.t("caintegrator2","creating");
x.t("caintegrator2","workspace");
x.t("caintegrator2","online");
x.t("caintegrator2","describe");
x.t("describe","concepts");
x.t("concepts","need");
}
