function FileData_Pairs(x)
{
x.t("searching","caintegrator2");
x.t("study","creating");
x.t("study","search");
x.t("study","view");
x.t("new","study");
x.t("new","studysearch");
x.t("reporter","annotations");
x.t("browse","functions");
x.t("overview","searching");
x.t("overview","creating");
x.t("overview","search");
x.t("gene","reporter");
x.t("creating","new");
x.t("part","study");
x.t("part","data");
x.t("search","browse");
x.t("search","overview");
x.t("search","clinical");
x.t("allow","search");
x.t("functions","caintegrator2");
x.t("annotations","may");
x.t("studysearch","overview");
x.t("may","part");
x.t("imaging","data");
x.t("view","gene");
x.t("data","uploaded");
x.t("data","genomic");
x.t("application","part");
x.t("uploaded","application");
x.t("caintegrator2","study");
x.t("caintegrator2","allow");
x.t("genomic","imaging");
x.t("clinical","data");
}
