function FileData_Pairs(x)
{
x.t("searching","study");
x.t("searching","studies");
x.t("searching","caintegrator2");
x.t("study","searching");
x.t("study","managing");
x.t("study","section");
x.t("managing","queries");
x.t("within","caintegrator2");
x.t("describes","processes");
x.t("overview","searching");
x.t("studies","within");
x.t("search","overview");
x.t("processes","searching");
x.t("section","describes");
x.t("section","include");
x.t("include","search");
x.t("topics","section");
x.t("caintegrator2","study");
x.t("caintegrator2","topics");
}
