function FileData_Pairs(x)
{
x.t("user","welcome");
x.t("getting","started");
x.t("new","caintegrator");
x.t("registering","new");
x.t("obtain","help");
x.t("logging","application");
x.t("introduces","general");
x.t("welcome","caintegrator");
x.t("started","caintegrator");
x.t("procedures","obtain");
x.t("workspace","using");
x.t("section","introduces");
x.t("section","include");
x.t("include","caintegrator");
x.t("caintegrator","user");
x.t("caintegrator","getting");
x.t("caintegrator","registering");
x.t("caintegrator","procedures");
x.t("caintegrator","workspace");
x.t("caintegrator","section");
x.t("caintegrator","topics");
x.t("help","logging");
x.t("help","caintegrator");
x.t("online","help");
x.t("application","support");
x.t("topics","section");
x.t("general","caintegrator");
x.t("using","online");
}
