function FileData_Pairs(x)
{
x.t("study","summary");
x.t("study","information");
x.t("study","log");
x.t("lists","step");
x.t("create","study");
x.t("summary","page");
x.t("open","clicking");
x.t("getting","started");
x.t("link","study");
x.t("clicking","study");
x.t("studies","study");
x.t("started","caintegrator");
x.t("viewing","existing");
x.t("step","used");
x.t("existing","studies");
x.t("caintegrator","viewing");
x.t("view","link");
x.t("viewing/editing","log");
x.t("page","lists");
x.t("information","viewing/editing");
x.t("used","create");
x.t("log","study");
x.t("log","open");
x.t("log","getting");
x.t("log","view");
}
