function FileData_Pairs(x)
{
x.t("searching","study");
x.t("searching","studies");
x.t("searching","caintegrator");
x.t("study","searching");
x.t("study","managing");
x.t("study","section");
x.t("managing","queries");
x.t("within","caintegrator");
x.t("describes","processes");
x.t("overview","searching");
x.t("studies","within");
x.t("search","overview");
x.t("processes","searching");
x.t("section","describes");
x.t("section","include");
x.t("include","search");
x.t("caintegrator","study");
x.t("caintegrator","topics");
x.t("topics","section");
}
