function FileData_Pairs(x)
{
x.t("study","gene");
x.t("create","plot");
x.t("regulated","parameters");
x.t("hit","create");
x.t("kaplan-meier","lots");
x.t("kaplan-meier","plots");
x.t("lots","select");
x.t("left","menu");
x.t("there's","plot");
x.t("menu","select");
x.t("gene","up/down");
x.t("gene","expression");
x.t("creating","kaplan-meier");
x.t("studies","performing");
x.t("up/down","regulated");
x.t("parameters","hit");
x.t("input","valid");
x.t("notice","there's");
x.t("select","study");
x.t("select","gene");
x.t("select","generate");
x.t("analyzing","studies");
x.t("performing","data");
x.t("generate","plot");
x.t("expression","data");
x.t("expression","tab");
x.t("valid","gene");
x.t("data","select");
x.t("data","analysis");
x.t("plots","creating");
x.t("plots","analyzing");
x.t("plot","left");
x.t("plot","notice");
x.t("plot","tab");
x.t("tab","input");
x.t("analysis","creating");
}
