function FileData_Pairs(x)
{
x.t("searching","caintegrator2");
x.t("study","managing");
x.t("managing","queries");
x.t("create","search");
x.t("later","edit");
x.t("editing","query");
x.t("edit","information");
x.t("search","query");
x.t("queries","searching");
x.t("queries","create");
x.t("queries","anaging");
x.t("saving","query");
x.t("query","later");
x.t("query","editing");
x.t("query","caintegrator2");
x.t("information","topics");
x.t("save","query");
x.t("topics","saving");
x.t("anaging","queries");
x.t("caintegrator2","study");
x.t("caintegrator2","save");
}
