function FileData_Pairs(x)
{
x.t("study","topics");
x.t("annotation","field");
x.t("annotation","import");
x.t("annotation","data");
x.t("files","configuration");
x.t("describes","configurations");
x.t("subject","annotation");
x.t("field","configuration");
x.t("sample","data");
x.t("configurations","importing");
x.t("configurations","section");
x.t("configurations","data");
x.t("supplemental","files");
x.t("importing","data");
x.t("section","describes");
x.t("section","include");
x.t("include","following");
x.t("configuration","sample");
x.t("configuration","supplemental");
x.t("configuration","imaging");
x.t("configuration","genomic");
x.t("configuration","delimited-text");
x.t("imaging","data");
x.t("import","annotation");
x.t("import","configurations");
x.t("data","study");
x.t("data","configuration");
x.t("data","import");
x.t("topics","section");
x.t("following","subject");
x.t("genomic","data");
x.t("delimited-text","annotation");
}
