function FileData_Pairs(x)
{
x.t("csv","file");
x.t("study","information");
x.t("annotation","imaging");
x.t("subject","annotation");
x.t("type","tab");
x.t("listed","column");
x.t("details","subjects");
x.t("file","(s)");
x.t("add","details");
x.t("results","subject");
x.t("results","type");
x.t("results","browsing");
x.t("configuring","results");
x.t("subjects","configuring");
x.t("headers","csv");
x.t("viewing","query");
x.t("annotations","listed");
x.t("imaging","data");
x.t("(s)","uploaded");
x.t("data","subject");
x.t("data","add");
x.t("data","viewing");
x.t("query","results");
x.t("information","using");
x.t("browsing","query");
x.t("column","headers");
x.t("uploaded","study");
x.t("using","results");
x.t("tab","results");
x.t("tab","annotations");
}
