ALTER TABLE abstract_persisted_analysis_job ADD COLUMN SERVER_CONNECTION_TYPE VARCHAR(15) AFTER RESULTS_ZIP_FILE_PATH;

UPDATE abstract_persisted_analysis_job
SET SERVER_CONNECTION_TYPE = "UNKNOWN"
WHERE TYPE like 'GISTIC';