ALTER TABLE GENOMIC_DATA_SOURCE_CONFIGURATION ADD COLUMN DNA_ANALYSIS_NUMBER_LEVEL_CALL INT AFTER DNA_ANALYSIS_USE_CGH_CALL;

UPDATE GENOMIC_DATA_SOURCE_CONFIGURATION SET DNA_ANALYSIS_USE_4_LEVEL_CALL = '3';