ALTER TABLE gistic_analysis MODIFY COLUMN AMPLIFICATIONS_THRESHOLD FLOAT DEFAULT NULL,
 MODIFY COLUMN DELETIONS_THRESHOLD FLOAT DEFAULT NULL,
 MODIFY COLUMN JOIN_SEGMENT_SIZE INTEGER DEFAULT NULL,
 MODIFY COLUMN QV_THRESHOLD FLOAT DEFAULT NULL;
