CREATE TABLE GISTIC_GENOMIC_REGION_REPORTER
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    BROAD_OR_FOCAL varchar(55),
    QVALUE DOUBLE,
    RESIDUAL_QVALUE DOUBLE,
    REGION_BOUNDARIES varchar(155),
    WIDE_PEAK_BOUNDARIES varchar(155),
    GENE_AMPLIFICATION_TYPE varchar(55),
    PRIMARY KEY (ID)
) TYPE=InnoDB;

CREATE TABLE ABSTRACT_COPY_NUMBER_ANALYSIS 
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    STUDY_SUBSCRIPTION_ID BIGINT,
    primary key (ID)
) TYPE=InnoDB;

CREATE TABLE COPY_NUMBER_ANALYSIS_SAMPLES
(
    COPY_NUMBER_ANALYSIS_ID BIGINT NOT NULL,
    SAMPLE_ID BIGINT NOT NULL,
    PRIMARY KEY (COPY_NUMBER_ANALYSIS_ID, SAMPLE_ID),
    KEY (COPY_NUMBER_ANALYSIS_ID),
    KEY (SAMPLE_ID)
) TYPE=InnoDB;

CREATE TABLE GISTIC_ANALYSIS
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME varchar(155),
    AMPLIFICATIONS_THRESHOLD DOUBLE,
    DELETIONS_THRESHOLD DOUBLE,
    GENOME_BUILD_INFORMATION varchar(155),
    JOIN_SEGMENT_SIZE DOUBLE,
    QUERY_OR_LIST_NAME varchar(155),
    QV_THRESHOLD DOUBLE,
    URL varchar(255),
    REPORTER_LIST_ID bigint,
    PRIMARY KEY (ID)
) TYPE=InnoDB;

ALTER TABLE COPY_NUMBER_ANALYSIS_SAMPLES ADD CONSTRAINT FK_COPY_NUMBER_ANALYSIS_SAMPLES_CN_ANALYSIS 
    FOREIGN KEY (COPY_NUMBER_ANALYSIS_ID) REFERENCES ABSTRACT_COPY_NUMBER_ANALYSIS (ID);

ALTER TABLE COPY_NUMBER_ANALYSIS_SAMPLES ADD CONSTRAINT FK_COPY_NUMBER_ANALYSIS_SAMPLES_SAMPLE 
    FOREIGN KEY (SAMPLE_ID) REFERENCES SAMPLE (ID);
    
ALTER TABLE GISTIC_ANALYSIS ADD CONSTRAINT FK_GISTIC_ANALYSIS_REPORTER_LIST 
    FOREIGN KEY (REPORTER_LIST_ID) REFERENCES REPORTER_LIST (ID);
    
ALTER TABLE ABSTRACT_COPY_NUMBER_ANALYSIS ADD CONSTRAINT FK_COPY_NUMBER_ANALSYIS_STUDY
    FOREIGN KEY (STUDY_SUBSCRIPTION_ID) REFERENCES STUDY_SUBSCRIPTION (ID);