CREATE TABLE GENE_LOCATION_CONFIGURATION (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  GENOME_BUILD_VERSION VARCHAR(25),
  STATUS VARCHAR(45),
  STATUS_DESCRIPTION VARCHAR(255),
  PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE GENE_CHROMOSOMAL_LOCATION (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  GENE_SYMBOL VARCHAR(55),
  CHROMOSOME VARCHAR(2),
  START_POSITION INTEGER,
  END_POSITION INTEGER,
  GENE_LOCATION_CONFIGURATION_ID BIGINT,
  PRIMARY KEY (ID)
) ENGINE = InnoDB;

ALTER TABLE GENE_CHROMOSOMAL_LOCATION ADD CONSTRAINT FK_GENE_CHROMOSOMAL_LOCATION_CONF 
    FOREIGN KEY (GENE_LOCATION_CONFIGURATION_ID)
    REFERENCES gene_location_configuration (ID);