ALTER TABLE SERVER_CONNECTION_PROFILE ADD COLUMN WEB_URL VARCHAR(255) AFTER URL;

UPDATE SERVER_CONNECTION_PROFILE SET WEB_URL = concat("https://", HOSTNAME, "/ncia") where HOSTNAME like "%imaging%";