CREATE TABLE COPY_NUMBER_ALTERATION_CRITERION 
(
    ID BIGINT NOT NULL AUTO_INCREMENT, 
    LOWER_LIMIT FLOAT, 
    UPPER_LIMIT FLOAT, 
    GENOMIC_INTERVAL_TYPE varchar(100),
    SEGMENT_BOUNDARY_TYPE varchar(100),
    CHROMOSOMAL_COORDINATE_LOW FLOAT,
    CHROMOSOMAL_COORDINATE_HIGH FLOAT,
    CHROMOSOME_NUMBER INTEGER,
    GENE_SYMBOL varchar(6000),
    PLATFORM_NAME varchar(255), 
    primary key (ID)
) Engine=InnoDB;