CREATE TABLE AUTHORIZED_STUDY_ELEMENTS_GROUP (
  ID bigint(20) NOT NULL auto_increment,
  GROUP_NAME varchar(255) default NULL,
  GROUP_DESCRIPTION varchar(255) default NULL,
  STUDY_CONFIGURATION_ID bigint(20) default NULL,
  LIST_INDEX int(11) default NULL,
  PRIMARY KEY (`ID`),
  KEY IDX_AUTHORIZED_STUDY_ELEMENTS_GROUP (`STUDY_CONFIGURATION_ID`)
) ENGINE=InnoDB;

ALTER TABLE AUTHORIZED_STUDY_ELEMENTS_GROUP ADD CONSTRAINT FK_AUTHORIZED_STUDY_ELEMENTS_GROUP_STUDY_CONFIGURATION
    FOREIGN KEY (STUDY_CONFIGURATION_ID) REFERENCES STUDY_CONFIGURATION (ID);

CREATE TABLE AUTHORIZED_AFD (
    ID bigint(20) NOT NULL auto_increment,
    AUTHORIZED_STUDY_ELEMENTS_GROUP_ID bigint(20) default NULL,
    ANNOTATION_FIELD_DESCRIPTOR_ID bigint(20) default NULL,
    LIST_INDEX int(11) default NULL,
    PRIMARY KEY (ID),
    KEY IDX_AUTHORIZED_AFD (AUTHORIZED_STUDY_ELEMENTS_GROUP_ID)
) ENGINE=InnoDB;

ALTER TABLE AUTHORIZED_AFD ADD CONSTRAINT FK_AUTHORIZED_AFD FOREIGN KEY (AUTHORIZED_STUDY_ELEMENTS_GROUP_ID) REFERENCES AUTHORIZED_STUDY_ELEMENTS_GROUP (ID);

CREATE TABLE AUTHORIZED_CRITERION (
    ID BIGINT(20) NOT NULL auto_increment,
    AUTHORIZED_STUDY_ELEMENTS_GROUP_ID BIGINT(20) default NULL,
    ABSTRACT_CRITERION_ID BIGINT(20) default NULL,
    LIST_INDEX int(11) default NULL,
    PRIMARY KEY (ID),
    KEY IDX_AUTHORIZED_CRITERION (AUTHORIZED_STUDY_ELEMENTS_GROUP_ID)
) ENGINE=InnoDB;

ALTER TABLE AUTHORIZED_CRITERION ADD CONSTRAINT FK_AUTHORIZED_CRITERION FOREIGN KEY (AUTHORIZED_STUDY_ELEMENTS_GROUP_ID) REFERENCES AUTHORIZED_STUDY_ELEMENTS_GROUP (ID);
    
CREATE TABLE AUTHORIZED_GDSC (
    ID bigint(20) NOT NULL auto_increment,
    AUTHORIZED_STUDY_ELEMENTS_GROUP_ID bigint(20) default NULL,
    GENOMIC_DATA_SOURCE_CONFIGURATION_ID bigint(20) default NULL,
    LIST_INDEX int(11) default NULL,
    PRIMARY KEY (ID),
    KEY IDX_AUTHORIZED_GDSC (`AUTHORIZED_STUDY_ELEMENTS_GROUP_ID`)
) ENGINE=InnoDB;

ALTER TABLE AUTHORIZED_GDSC ADD CONSTRAINT FK_AUTHORIZED_GDS
    FOREIGN KEY (AUTHORIZED_STUDY_ELEMENTS_GROUP_ID) REFERENCES AUTHORIZED_STUDY_ELEMENTS_GROUP (ID); 
