ALTER TABLE AUTHORIZED_STUDY_ELEMENTS_GROUP ADD COLUMN GROUP_ID BIGINT;
ALTER TABLE AUTHORIZED_STUDY_ELEMENTS_GROUP ADD CONSTRAINT FK_GROUP FOREIGN KEY (GROUP_ID) REFERENCES CSM_GROUP(GROUP_ID);
UPDATE AUTHORIZED_STUDY_ELEMENTS_GROUP aseg SET aseg.GROUP_ID = (SELECT ID FROM CSM_GROUP WHERE GROUP_NAME = aseg.GROUP_NAME);

ALTER TABLE AUTHORIZED_STUDY_ELEMENTS_GROUP CHANGE GROUP_ID GROUP_ID BIGINT NOT NULL;
ALTER TABLE AUTHORIZED_STUDY_ELEMENTS_GROUP DROP COLUMN GROUP_NAME;
ALTER TABLE AUTHORIZED_STUDY_ELEMENTS_GROUP DROP COLUMN GROUP_DESCRIPTION;
