ALTER TABLE SAMPLE ADD COLUMN CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
-- Set existing samples creation dates to be 1 year in the past.
UPDATE SAMPLE SET CREATION_DATE = now() - INTERVAL 1 YEAR;
ALTER TABLE SAMPLE CHANGE CREATION_DATE CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;