
ALTER TABLE CSM_GROUP DROP FOREIGN KEY FK_APPLICATION_GROUP;
ALTER TABLE CSM_FILTER_CLAUSE DROP FOREIGN KEY FK_APPLICATION_FILTER_CLAUSE;
ALTER TABLE CSM_MAPPING DROP FOREIGN KEY FK_PE_APPLICATION;
ALTER TABLE CSM_PROTECTION_ELEMENT DROP FOREIGN KEY FK_PE_APPLICATION2;
ALTER TABLE CSM_PROTECTION_GROUP DROP FOREIGN KEY FK_PG_APPLICATION;
ALTER TABLE CSM_PROTECTION_GROUP DROP FOREIGN KEY FK_PROTECTION_GROUP;
ALTER TABLE CSM_PG_PE DROP FOREIGN KEY FK_PROTECTION_ELEMENT_PROTECTION_GROUP;
ALTER TABLE CSM_PG_PE DROP FOREIGN KEY FK_PROTECTION_GROUP_PROTECTION_ELEMENT;
ALTER TABLE CSM_ROLE DROP FOREIGN KEY FK_APPLICATION_ROLE;
ALTER TABLE CSM_ROLE_PRIVILEGE DROP FOREIGN KEY FK_PRIVILEGE_ROLE;
ALTER TABLE CSM_ROLE_PRIVILEGE DROP FOREIGN KEY FK_ROLE;
ALTER TABLE CSM_USER_GROUP DROP FOREIGN KEY FK_USER_GROUP;
ALTER TABLE CSM_USER_GROUP DROP FOREIGN KEY FK_UG_GROUP;
ALTER TABLE CSM_USER_GROUP_ROLE_PG DROP FOREIGN KEY FK_USER_GROUP_ROLE_PROTECTION_GROUP_GROUPS;
ALTER TABLE CSM_USER_GROUP_ROLE_PG DROP FOREIGN KEY FK_USER_GROUP_ROLE_PROTECTION_GROUP_ROLE;
ALTER TABLE CSM_USER_GROUP_ROLE_PG DROP FOREIGN KEY FK_USER_GROUP_ROLE_PROTECTION_GROUP_PROTECTION_GROUP;
ALTER TABLE CSM_USER_GROUP_ROLE_PG DROP FOREIGN KEY FK_USER_GROUP_ROLE_PROTECTION_GROUP_USER;
ALTER TABLE CSM_USER_PE DROP FOREIGN KEY FK_PE_USER;
ALTER TABLE CSM_USER_PE DROP FOREIGN KEY FK_PROTECTION_ELEMENT_USER;

DROP TABLE IF EXISTS CSM_APPLICATION;
DROP TABLE IF EXISTS CSM_GROUP;
DROP TABLE IF EXISTS CSM_PRIVILEGE;
DROP TABLE IF EXISTS CSM_FILTER_CLAUSE;
DROP TABLE IF EXISTS CSM_MAPPING;
DROP TABLE IF EXISTS CSM_PROTECTION_ELEMENT;
DROP TABLE IF EXISTS CSM_PROTECTION_GROUP;
DROP TABLE IF EXISTS CSM_PG_PE;
DROP TABLE IF EXISTS CSM_ROLE;
DROP TABLE IF EXISTS CSM_ROLE_PRIVILEGE;
DROP TABLE IF EXISTS CSM_USER;
DROP TABLE IF EXISTS CSM_USER_GROUP;
DROP TABLE IF EXISTS CSM_USER_GROUP_ROLE_PG;
DROP TABLE IF EXISTS CSM_USER_PE;

COMMIT;
