function  WWHBookData_Files(P)
{
P.fA("Welcome to caIntegrator2 Online Help","Welcome.1.1.html");
P.fA("Getting Started with caIntegrator2","Getting_Started.2.1.html");
P.fA("About caIntegrator2","Getting_Started.2.2.html");
P.fA("Using Online Help","Getting_Started.2.3.html");
P.fA("Logging In","Getting_Started.2.4.html");
P.fA("Using the caIntegrator2 Workspace","Getting_Started.2.5.html");
P.fA("caIntegrator2 Functions","Getting_Started.2.6.html");
P.fA("Logging Out","Getting_Started.2.7.html");
P.fA("Application Support","Getting_Started.2.8.html");
P.fA("Creating a New Study","CreatingNewStudy.3.1.html");
P.fA("Creating a Study \u2013 Overview","CreatingNewStudy.3.2.html");
P.fA("Configuring and Deploying Study","CreatingNewStudy.3.3.html");
P.fA("Creating/Editing a Study","CreatingNewStudy.3.4.html");
P.fA("Adding Clinical Data","CreatingNewStudy.3.5.html");
P.fA("Assigning An Identifier or Annotation","CreatingNewStudy.3.6.html");
P.fA("Searching for Annotation Definitions","CreatingNewStudy.3.7.html");
P.fA("Editing a Study","CreatingNewStudy.3.8.html");
P.fA("Editing Survival Values","CreatingNewStudy.3.9.html");
P.fA("Adding Genomic Data","CreatingNewStudy.3.10.html");
P.fA("Editing Genomic Data","CreatingNewStudy.3.11.html");
P.fA("Mapping Genomic Data to Clinical Data","CreatingNewStudy.3.12.html");
P.fA("Uploading Control Samples","CreatingNewStudy.3.13.html");
P.fA("Adding Imaging Data","CreatingNewStudy.3.14.html");
P.fA("Deploying the Study","CreatingNewStudy.3.15.html");
P.fA("Managing a Study","CreatingNewStudy.3.16.html");
P.fA("Managing Platforms","CreatingNewStudy.3.17.html");
P.fA("Searching a caIntegrator2 Study","SearchingWithinAStudy.4.1.html");
P.fA("Search Overview","SearchingWithinAStudy.4.2.html");
P.fA("Searching a Study","SearchingWithinAStudy.4.3.html");
P.fA("Columns and Sorting Tabs","SearchingWithinAStudy.4.4.html");
P.fA("Managing Queries","SearchingWithinAStudy.4.5.html");
P.fA("Saving a Query","SearchingWithinAStudy.4.6.html");
P.fA("Editing a Query","SearchingWithinAStudy.4.7.html");
P.fA("Exporting Query Results","SearchingWithinAStudy.4.8.html");
P.fA("Viewing Search Results","View%20Results.5.1.html");
P.fA("Search Results Overview","View%20Results.5.2.html");
P.fA("Browsing Search Results","View%20Results.5.3.html");
P.fA("Genomic Data","View%20Results.5.4.html");
P.fA("Imaging Data Results","View%20Results.5.5.html");
P.fA("Exporting Data","View%20Results.5.6.html");
P.fA("Analyzing Studies","PerformingAnalysis.6.1.html");
P.fA("Performing Data Analysis","PerformingAnalysis.6.2.html");
P.fA("Creating Kaplan-Meier Plots","PerformingAnalysis.6.3.html");
P.fA("KM Plot for Annotations","PerformingAnalysis.6.4.html");
P.fA("KM Plot for Gene Expression","PerformingAnalysis.6.5.html");
P.fA("KM Plot for Queries","PerformingAnalysis.6.6.html");
P.fA("Gene Expression Value Plot for Annotation","PerformingAnalysis.6.7.html");
P.fA("Gene Expression Value Plot for Genomic Queries","PerformingAnalysis.6.8.html");
P.fA("Gene Expression Value Plot for Cinical Queries","PerformingAnalysis.6.9.html");
P.fA("Analyzing Data with GenePattern","PerformingAnalysis.6.10.html");
P.fA("Glossary","Glossary.7.1.html");
P.fA("Data Import Configurations","appdx%20data%20import.8.1.html");
P.fA("Delimited-Text Annotation Import","appdx%20data%20import.8.2.html");
P.fA("Annotation Field Configuration","appdx%20data%20import.8.3.html");
P.fA("Sample Data Configuration","appdx%20data%20import.8.4.html");
P.fA("Genomic Data Configuration","appdx%20data%20import.8.5.html");
P.fA("Imaging Data Configuration","appdx%20data%20import.8.6.html");
P.fA("Index","Index.9.1.html");
}
