ALTER TABLE GENOMIC_DATA_SOURCE_CONFIGURATION ADD COLUMN DNA_ANALYSIS_USE_CGH_CALL TINYINT AFTER DNA_ANALYSIS_RANDOM_NUMBER_SEED;

UPDATE GENOMIC_DATA_SOURCE_CONFIGURATION SET DNA_ANALYSIS_USE_CGH_CALL = '0';