function FileData_Pairs(x)
{
x.t("sidebar","workspace");
x.t("left","sidebar");
x.t("listed","left");
x.t("getting","started");
x.t("access","caintegrator2");
x.t("studies","logging");
x.t("enables","quick");
x.t("welcome","workspace");
x.t("welcome","caintegrator2");
x.t("started","caintegrator2");
x.t("quick","access");
x.t("functions","options");
x.t("functions","viewing");
x.t("functions","information");
x.t("options","listed");
x.t("viewing","existing");
x.t("workspace","getting");
x.t("workspace","enables");
x.t("workspace","welcome");
x.t("workspace","caintegrator2");
x.t("login","access");
x.t("existing","studies");
x.t("information","login");
x.t("caintegrator2","welcome");
x.t("caintegrator2","functions");
x.t("caintegrator2","workspace");
}
