function FileData_Pairs(x)
{
x.t("searching","studies");
x.t("searching","caintegrator2");
x.t("study","searching");
x.t("study","section");
x.t("managing","queries");
x.t("within","caintegrator2");
x.t("describes","processes");
x.t("launching","search");
x.t("browse","tools");
x.t("overview","launching");
x.t("studies","within");
x.t("search","managing");
x.t("search","browse");
x.t("search","overview");
x.t("processes","searching");
x.t("section","describes");
x.t("section","include");
x.t("include","search");
x.t("tools","topics");
x.t("topics","section");
x.t("using","search");
x.t("caintegrator2","study");
x.t("caintegrator2","using");
}
