function FileData_Pairs(x)
{
x.t("user","register");
x.t("icon","ncia");
x.t("register","ncia");
x.t("time","user");
x.t("column.the","ncia");
x.t("access","images");
x.t("access","ncia");
x.t("results","search");
x.t("results","clinical");
x.t("obtain","username");
x.t("search","results");
x.t("web","site");
x.t("appears","first");
x.t("first","time");
x.t("viewing","results");
x.t("accessing","ncia");
x.t("report","access");
x.t("report","viewing");
x.t("report","accessing");
x.t("report","follow");
x.t("reports","accessing");
x.t("follow","steps");
x.t("steps","click");
x.t("click","ncia");
x.t("username","password");
x.t("ncia","icon");
x.t("ncia","obtain");
x.t("ncia","web");
x.t("ncia","image");
x.t("site","appears");
x.t("image","column.the");
x.t("image","clinical");
x.t("password","log");
x.t("log","access");
x.t("clinical","report");
x.t("clinical","reports");
}
