function FileData_Pairs(x)
{
x.t("searching","caintegrator2");
x.t("study","manage");
x.t("available","further");
x.t("editing","query");
x.t("link","next");
x.t("list","save");
x.t("name","list");
x.t("edit","link");
x.t("parameters","available");
x.t("further","editing");
x.t("queries","editing");
x.t("queries","manage");
x.t("next","query");
x.t("prepopulated","query");
x.t("defintion","page");
x.t("click","edit");
x.t("page","prepopulated");
x.t("query","searching");
x.t("query","name");
x.t("query","parameters");
x.t("query","defintion");
x.t("query","query");
x.t("query","definitions");
x.t("query","diting");
x.t("query","update");
x.t("save","queries");
x.t("manage","queries");
x.t("manage","query");
x.t("definitions","click");
x.t("caintegrator2","study");
x.t("diting","query");
x.t("update","query");
}
