function FileData_Pairs(x)
{
x.t("related","topics");
x.t("displays","patients");
x.t("sort","patients");
x.t("list","further");
x.t("results","search");
x.t("results","viewing");
x.t("results","ihc");
x.t("filter","queries");
x.t("name","additional");
x.t("patientdid","list");
x.t("further","filter");
x.t("search","results");
x.t("search","ihc");
x.t("patients","patientdid");
x.t("patients","selected");
x.t("patients","using");
x.t("selected","ihc");
x.t("queries","sort");
x.t("red","triangles");
x.t("select","save");
x.t("viewing","results");
x.t("report","displays");
x.t("level","expression");
x.t("ihc","level");
x.t("additional","information");
x.t("expression","search");
x.t("expression","report");
x.t("expression","page");
x.t("page","select");
x.t("information","related");
x.t("save","patients");
x.t("triangles","column");
x.t("column","name");
x.t("using","red");
}
