function FileData_Pairs(x)
{
x.t("getting","started");
x.t("link","upper");
x.t("upper","right-hand");
x.t("corner","application");
x.t("right-hand","corner");
x.t("obtain","help");
x.t("logging","using");
x.t("logging","log");
x.t("introduces","general");
x.t("started","caintegrator2");
x.t("procedures","obtain");
x.t("workspace","logging");
x.t("section","introduces");
x.t("section","include");
x.t("click","logout");
x.t("include","caintegrator2");
x.t("help","caintegrator2");
x.t("application","support");
x.t("topics","section");
x.t("general","caintegrator2");
x.t("using","caintegrator2");
x.t("logout","link");
x.t("caintegrator2","getting");
x.t("caintegrator2","logging");
x.t("caintegrator2","procedures");
x.t("caintegrator2","workspace");
x.t("caintegrator2","section");
x.t("caintegrator2","click");
x.t("caintegrator2","topics");
x.t("log","caintegrator2");
}
