function FileData_Pairs(x)
{
x.t("getting","started");
x.t("obtain","help");
x.t("introduces","general");
x.t("started","caintegrator2");
x.t("procedures","obtain");
x.t("workspace","logging");
x.t("section","introduces");
x.t("section","include");
x.t("include","using");
x.t("help","caintegrator2");
x.t("topics","section");
x.t("general","caintegrator2");
x.t("using","caintegrator2");
x.t("caintegrator2","getting");
x.t("caintegrator2","procedures");
x.t("caintegrator2","workspace");
x.t("caintegrator2","section");
x.t("caintegrator2","topics");
}
