function FileData_Pairs(x)
{
x.t("normalized","expression");
x.t("organized","grid");
x.t("working","search");
x.t("sample","cell");
x.t("reporter","given");
x.t("results","working");
x.t("results","gene");
x.t("results","queries");
x.t("results","viewing");
x.t("gene","expression");
x.t("search","results");
x.t("cell","contents");
x.t("queries","return");
x.t("grid","samples");
x.t("reporters","row");
x.t("viewing","results");
x.t("row","headings");
x.t("samples","column");
x.t("headings","normalized");
x.t("headings","reporters");
x.t("return","gene");
x.t("given","sample");
x.t("given","reporter");
x.t("value","given");
x.t("expression","value");
x.t("expression","query");
x.t("expression","data");
x.t("query","results");
x.t("data","organized");
x.t("column","headings");
}
