function FileData_Pairs(x)
{
x.t("managing","user");
x.t("managing","ownership");
x.t("describes","process");
x.t("sidebar","browser");
x.t("user","account");
x.t("user","management");
x.t("user","accounts");
x.t("left","sidebar");
x.t("browser","admin");
x.t("access","studies");
x.t("account","administration");
x.t("creating","managing");
x.t("studies","caintegrator2");
x.t("discusses","processes");
x.t("tasks","visible");
x.t("ownership","access");
x.t("options","performing");
x.t("processes","managing");
x.t("section","describes");
x.t("admin","privileges");
x.t("performing","user");
x.t("process","creating");
x.t("privileges","administering");
x.t("administration","user");
x.t("administration","section");
x.t("administering","caintegrator2");
x.t("management","tasks");
x.t("using","upt");
x.t("accounts","using");
x.t("accounts","caintegrator2");
x.t("caintegrator2","user");
x.t("caintegrator2","left");
x.t("caintegrator2","discusses");
x.t("caintegrator2","options");
x.t("visible","caintegrator2");
}
