function FileData_Pairs(x)
{
x.t("appendix","describes");
x.t("appendix","include");
x.t("study","topics");
x.t("annotation","field");
x.t("annotation","import");
x.t("describes","configurations");
x.t("subject","clinical");
x.t("field","configuration");
x.t("sample","data");
x.t("configurations","appendix");
x.t("configurations","importing");
x.t("configurations","data");
x.t("importing","data");
x.t("include","following");
x.t("configuration","sample");
x.t("configuration","imaging");
x.t("configuration","genomic");
x.t("configuration","delimited-text");
x.t("imaging","data");
x.t("import","configurations");
x.t("import","page");
x.t("page","annotation");
x.t("data","study");
x.t("data","configuration");
x.t("data","import");
x.t("topics","appendix");
x.t("following","subject");
x.t("genomic","data");
x.t("clinical","data");
x.t("delimited-text","annotation");
}
