function FileData_Pairs(x)
{
x.t("sidebar","workspace");
x.t("left","sidebar");
x.t("orkspace","caintegrator2");
x.t("listed","left");
x.t("getting","started");
x.t("access","caintegrator2");
x.t("link","upper");
x.t("upper","right-hand");
x.t("corner","application");
x.t("right-hand","corner");
x.t("enables","quick");
x.t("started","caintegrator2");
x.t("quick","access");
x.t("functions","options");
x.t("functions","page");
x.t("functions","information");
x.t("options","listed");
x.t("workspace","getting");
x.t("workspace","enables");
x.t("workspace","using");
x.t("workspace","caintegrator2");
x.t("click","logout");
x.t("page","log");
x.t("information","access");
x.t("application","support");
x.t("using","caintegrator2");
x.t("logout","link");
x.t("caintegrator2","orkspace");
x.t("caintegrator2","functions");
x.t("caintegrator2","workspace");
x.t("caintegrator2","click");
x.t("caintegrator2","using");
x.t("log","caintegrator2");
}
