function FileData_Pairs(x)
{
x.t("csv","file");
x.t("columns","sorting");
x.t("columns","tab");
x.t("study","information");
x.t("subject","configuring");
x.t("listed","column");
x.t("details","single");
x.t("single","subject");
x.t("file","(s)");
x.t("add","details");
x.t("results","browsing");
x.t("results","clinical");
x.t("configuring","columns");
x.t("headers","csv");
x.t("viewing","query");
x.t("annotations","listed");
x.t("sorting","tabs");
x.t("imaging","data");
x.t("(s)","uploaded");
x.t("data","add");
x.t("data","viewing");
x.t("data","clinical");
x.t("query","results");
x.t("information","using");
x.t("browsing","query");
x.t("column","headers");
x.t("uploaded","study");
x.t("using","columns");
x.t("tab","columns");
x.t("tab","annotations");
x.t("clinical","imaging");
}
