function FileData_Pairs(x)
{
x.t("sidebar","workspace");
x.t("left","sidebar");
x.t("listed","left");
x.t("getting","started");
x.t("access","caintegrator2");
x.t("enables","quick");
x.t("started","caintegrator2");
x.t("quick","access");
x.t("functions","logging");
x.t("functions","options");
x.t("functions","information");
x.t("options","listed");
x.t("workspace","getting");
x.t("workspace","enables");
x.t("workspace","using");
x.t("workspace","caintegrator2");
x.t("information","access");
x.t("using","caintegrator2");
x.t("caintegrator2","functions");
x.t("caintegrator2","workspace");
x.t("caintegrator2","using");
}
