function FileData_Pairs(x)
{
x.t("searching","caintegrator");
x.t("introduce","caintegrator");
x.t("study","welcome");
x.t("study","viewing");
x.t("user","accounts");
x.t("getting","started");
x.t("new","study");
x.t("need","know");
x.t("results","analyzing");
x.t("creating","new");
x.t("studies","administering");
x.t("welcome","caintegrator");
x.t("started","caintegrator");
x.t("know","caintegrator");
x.t("viewing","query");
x.t("workspace","searching");
x.t("analyzing","studies");
x.t("caintegrator","study");
x.t("caintegrator","getting");
x.t("caintegrator","creating");
x.t("caintegrator","workspace");
x.t("caintegrator","online");
x.t("caintegrator","describe");
x.t("online","help");
x.t("help","welcome");
x.t("help","following");
x.t("query","results");
x.t("topics","introduce");
x.t("administering","user");
x.t("following","topics");
x.t("using","online");
x.t("accounts","using");
x.t("describe","concepts");
x.t("concepts","need");
}
