function FileData_Pairs(x)
{
x.t("study","adding/editing");
x.t("annotation","data");
x.t("annotation","genomic");
x.t("files","map");
x.t("files","mapped");
x.t("source","files");
x.t("subject","annotation");
x.t("adding/editing","genomic");
x.t("caarray","genomic");
x.t("new","study");
x.t("imported","parsed");
x.t("creating","new");
x.t("stored","supplemental");
x.t("map","caarray");
x.t("supplemental","files");
x.t("mapped","mapping");
x.t("parsed","stored");
x.t("types","imported");
x.t("imaging","data");
x.t("sources","data");
x.t("caintegrator","integrate");
x.t("data","subject");
x.t("data","creating");
x.t("data","sources");
x.t("data","goal");
x.t("data","two");
x.t("data","mapping");
x.t("data","uploaded");
x.t("goal","caintegrator");
x.t("two","types");
x.t("mapping","files");
x.t("mapping","genomic");
x.t("uploaded","source");
x.t("genomic","imaging");
x.t("genomic","data");
x.t("integrate","data");
}
