function FileData_Pairs(x)
{
x.t("searching","caintegrator2");
x.t("introduce","caintegrator2");
x.t("study","analyzing");
x.t("study","using");
x.t("getting","started");
x.t("new","study");
x.t("need","know");
x.t("creating","new");
x.t("studies","glossary");
x.t("welcome","caintegrator2");
x.t("glossary","using");
x.t("started","caintegrator2");
x.t("know","caintegrator2");
x.t("workspace","searching");
x.t("analyzing","studies");
x.t("caintegrator","workspace");
x.t("online","help");
x.t("help","welcome");
x.t("help","following");
x.t("topics","introduce");
x.t("following","topics");
x.t("using","caintegrator");
x.t("using","online");
x.t("caintegrator2","study");
x.t("caintegrator2","getting");
x.t("caintegrator2","creating");
x.t("caintegrator2","online");
x.t("caintegrator2","describe");
x.t("describe","concepts");
x.t("concepts","need");
}
