function FileData_Pairs(x)
{
x.t("describes","search");
x.t("results","overview");
x.t("results","viewing");
x.t("results","section");
x.t("results","caintegrator");
x.t("overview","browsing");
x.t("search","results");
x.t("queries","topics");
x.t("viewing","query");
x.t("section","describes");
x.t("section","include");
x.t("include","following");
x.t("caintegrator","returns");
x.t("query","results");
x.t("browsing","query");
x.t("topics","section");
x.t("following","query");
x.t("returns","queries");
}
