function FileData_Pairs(x)
{
x.t("searching","caintegrator");
x.t("study","managing");
x.t("managing","queries");
x.t("tab-delimited","text");
x.t("text","file");
x.t("file","information");
x.t("results","searching");
x.t("results","exporting");
x.t("results","running");
x.t("search","export");
x.t("queries","exporting");
x.t("exporting","query");
x.t("exporting","data");
x.t("running","search");
x.t("caintegrator","study");
x.t("query","results");
x.t("information","exporting");
x.t("result","subset");
x.t("export","result");
x.t("subset","tab-delimited");
}
