function FileData_Pairs(x)
{
x.t("user","using");
x.t("getting","started");
x.t("new","caintegrator2");
x.t("registering","new");
x.t("obtain","help");
x.t("logging","application");
x.t("introduces","general");
x.t("started","caintegrator2");
x.t("procedures","obtain");
x.t("workspace","using");
x.t("section","introduces");
x.t("section","include");
x.t("include","caintegrator2");
x.t("help","logging");
x.t("help","caintegrator2");
x.t("online","help");
x.t("application","support");
x.t("topics","section");
x.t("general","caintegrator2");
x.t("using","online");
x.t("using","caintegrator2");
x.t("caintegrator2","user");
x.t("caintegrator2","getting");
x.t("caintegrator2","registering");
x.t("caintegrator2","procedures");
x.t("caintegrator2","workspace");
x.t("caintegrator2","section");
x.t("caintegrator2","topics");
}
