function FileData_Pairs(x)
{
x.t("study","working");
x.t("study","existing");
x.t("study","page");
x.t("annotation","group");
x.t("working","annotations");
x.t("editing","annotation");
x.t("new","study");
x.t("group","editing");
x.t("group","creating");
x.t("group","edit");
x.t("group","button");
x.t("group","click");
x.t("overview","editing");
x.t("creating","new");
x.t("edit","study");
x.t("edit","annotation");
x.t("edit","group");
x.t("annotations","overview");
x.t("click","edit");
x.t("existing","annotation");
x.t("page","study");
}
