function FileData_Pairs(x)
{
x.t("legend","printed");
x.t("legend","graph");
x.t("create","plot");
x.t("kaplan-meier","plots");
x.t("text","anymore");
x.t("group","appears");
x.t("validate","number");
x.t("validate","groups");
x.t("studies","performing");
x.t("creating","kaplan-meier");
x.t("subjects","group");
x.t("patients","legend");
x.t("error","text");
x.t("red","error");
x.t("appears","embedded");
x.t("number","subjects");
x.t("annotations","create");
x.t("annotations","analyzing");
x.t("annotations","plot");
x.t("analyzing","studies");
x.t("groups","patients");
x.t("performing","data");
x.t("embedded","legend");
x.t("printed","red");
x.t("data","analysis");
x.t("graph","validate");
x.t("plots","plot");
x.t("plot","annotations");
x.t("plot","graph");
x.t("analysis","creating");
}
