function FileData_Pairs(x)
{
x.t("lists","output");
x.t("displays","query");
x.t("p53","search");
x.t("results","displays");
x.t("results","p53");
x.t("results","search");
x.t("results","viewing");
x.t("results","ihc");
x.t("results","generated");
x.t("results","view");
x.t("results","following");
x.t("name","lists");
x.t("search","results");
x.t("search","function");
x.t("viewing","results");
x.t("function","clinical");
x.t("loss","expression");
x.t("reports","ihc");
x.t("level","expression");
x.t("ihc","loss");
x.t("ihc","level");
x.t("generated","search");
x.t("generated","query");
x.t("view","results");
x.t("expression","search");
x.t("output","generated");
x.t("query","name");
x.t("following","results");
x.t("clinical","reports");
}
